version: '3.8'

x-api-vars: &api-vars
  COMPOSE_PROJECT_NAME: nim_api_development
  NIM_ENV: development

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment: *api-vars # 環境変数の読込み
    ports:
      - "50000:5000" #バインドするポート番号(コンテナのそとからのアクセスは50000ポートで指定)
    tty: true
    privileged: true